// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48x9vaTBEIYMrgzkwJdxT8Lc3TLikeXY',
    appId: '1:1048953578882:android:ab81bedd43fbdaffb8db9b',
    messagingSenderId: '1048953578882',
    projectId: 'agri-demo-7fff6',
    databaseURL: 'https://agri-demo-7fff6-default-rtdb.firebaseio.com',
    storageBucket: 'agri-demo-7fff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-yGB0pyFeLDGgN6M4IMAazJnTTTwjYQ',
    appId: '1:1048953578882:ios:10392835b21ab172b8db9b',
    messagingSenderId: '1048953578882',
    projectId: 'agri-demo-7fff6',
    databaseURL: 'https://agri-demo-7fff6-default-rtdb.firebaseio.com',
    storageBucket: 'agri-demo-7fff6.firebasestorage.app',
    iosBundleId: 'com.aramwest.agrihubios.production',
  );
}
